export { default as Template } from './Template'
export { default as GettingStarted } from './GettingStarted'
export { default as AddMenuTab } from './AddMenuTab'
export { default as AddPage } from './AddPage'
export { default as HowToStart } from './HowToStart'
